apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: baremetal-clusters
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            nerc.mghpcc.org/platform: baremetal
